language: python

python:
  - 3.6

services:
  - mysql

#before_install:

#install:
#  - pip install -r smartcampus/requirements.txt

#after_install:

#before_script:

script:
  - python3 smartcampus/manage.py test
  - coverage run smartcampus/manage.py test core -v 2

after_success:
  - coverage html

#after_script:



