# Generated by Django 2.1.1 on 2018-11-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airquality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('air_quality_level', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_airquality',
            },
        ),
        migrations.CreateModel(
            name='Campusbuilding',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_campusbuilding',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=17, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('pres', models.FloatField(blank=True, null=True)),
                ('hum', models.FloatField(blank=True, null=True)),
                ('gas', models.FloatField(blank=True, null=True)),
                ('lux', models.IntegerField(blank=True, null=True)),
                ('db', models.FloatField(blank=True, null=True)),
                ('dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='Decibel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('decibel_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_decibel',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, null=True)),
                ('email', models.EmailField(max_length=70, null=True)),
                ('feedback', models.CharField(max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('humidity_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_humidity',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_location',
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pressure_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
            options={
                'db_table': 'core_pressure',
            },
        ),
        migrations.CreateModel(
            name='Sensortype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_sensortype',
            },
        ),
        migrations.CreateModel(
            name='Singleboardcomputer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('single_board_computer_name', models.CharField(max_length=220)),
                ('operating_system', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
            options={
                'db_table': 'core_singleboardcomputer',
            },
        ),
        migrations.CreateModel(
            name='Singleboardcomputertype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('computer_type', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_singleboardcomputertype',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
            options={
                'db_table': 'core_temperature',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_user',
            },
        ),
        migrations.AddField(
            model_name='singleboardcomputer',
            name='single_board_computer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Singleboardcomputertype'),
        ),
        migrations.AddField(
            model_name='humidity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='decibel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='campusbuilding',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='airquality',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
