# Generated by Django 2.1.1 on 2018-10-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='data',
            name='mac_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
