# Generated by Django 2.1.1 on 2018-10-06 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_airquality_decibel_humidity_pressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusBuilding',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleBoardComputer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('single_board_computer_name', models.CharField(max_length=220)),
                ('operating_system', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleBoardComputerType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('computer_type', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='airquality',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='decibel',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='humidity',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='pressure',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='pressure',
            old_name='pressure_value',
            new_name='pressure_level',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='temperature',
            new_name='temperature_level',
        ),
        migrations.AddField(
            model_name='airquality',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=60),
        ),
        migrations.AddField(
            model_name='decibel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=60),
        ),
        migrations.AddField(
            model_name='humidity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=60),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pressure',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=60),
        ),
        migrations.AddField(
            model_name='temperature',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=60),
        ),
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=60),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=220),
        ),
        migrations.AddField(
            model_name='singleboardcomputer',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='singleboardcomputer',
            name='single_board_computer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SingleBoardComputerType'),
        ),
        migrations.AddField(
            model_name='campusbuilding',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
