# Generated by Django 2.1.1 on 2018-10-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181006_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airquality',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='campusbuilding',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='decibel',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='humidity',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='pressure',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='singleboardcomputer',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='location_id',
            new_name='location',
        ),
    ]
