# Generated by Django 2.1.1 on 2018-10-06 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181006_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='air_quality',
        ),
        migrations.RemoveField(
            model_name='data',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='data',
            name='decibel',
        ),
        migrations.RemoveField(
            model_name='data',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='data',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='data',
            name='temperature',
        ),
        migrations.AddField(
            model_name='data',
            name='db',
            field=models.FloatField(blank=True, db_column='db', default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='dt',
            field=models.DateTimeField(db_column='dt', default=datetime.datetime.now, max_length=60),
        ),
        migrations.AddField(
            model_name='data',
            name='gas',
            field=models.IntegerField(db_column='gas', default=None),
        ),
        migrations.AddField(
            model_name='data',
            name='hum',
            field=models.FloatField(blank=True, db_column='hum', default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='lux',
            field=models.IntegerField(db_column='lux', null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='mac',
            field=models.CharField(db_column='mac', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pres',
            field=models.FloatField(blank=True, db_column='pres', default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='temp',
            field=models.FloatField(blank=True, db_column='temp', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='data',
            table='zeroData',
        ),
    ]
