# Generated by Django 2.1.1 on 2018-10-06 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181006_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='zeroData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_column='mac', max_length=100, null=True)),
                ('dt', models.DateTimeField(db_column='dt', default=datetime.datetime.now, max_length=60)),
                ('temp', models.FloatField(blank=True, db_column='temp', default=None, null=True)),
                ('hum', models.FloatField(blank=True, db_column='hum', default=None, null=True)),
                ('pres', models.FloatField(blank=True, db_column='pres', default=None, null=True)),
                ('gas', models.IntegerField(db_column='gas', default=None)),
                ('db', models.FloatField(blank=True, db_column='db', default=None, null=True)),
                ('lux', models.IntegerField(db_column='lux', null=True)),
            ],
            options={
                'db_table': 'zeroData',
            },
        ),
        migrations.AlterModelTable(
            name='data',
            table='Data',
        ),
    ]
