# Generated by Django 2.1.1 on 2018-10-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181006_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='zerodata',
            options={'managed': False},
        ),
    ]
