# Generated by Django 2.1.1 on 2018-10-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181006_2137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table=None,
        ),
        migrations.AlterModelTable(
            name='zerodata',
            table=None,
        ),
    ]
