# Generated by Django 2.1.1 on 2018-10-06 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181006_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='db',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='gas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='hum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='lux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='pres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singleboardcomputer',
            name='single_board_computer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Singleboardcomputertype'),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='db',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='gas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='hum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='lux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='pres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerodata',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
