# Generated by Django 2.1.1 on 2018-10-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181008_1011'),
        ('core', '0017_auto_20181008_1938'),
    ]

    operations = [
    ]
