# Generated by Django 2.1.1 on 2018-10-30 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20181030_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, null=True)),
                ('email', models.DateTimeField(null=True)),
                ('feedback', models.CharField(max_length=220, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='singleboardcomputer',
            name='single_board_computer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Singleboardcomputertype'),
        ),
    ]
